"""change username uniqueness to false

Revision ID: 40d0060088d6
Revises: 1b9203eb9391
Create Date: 2026-08-04 15:50:32.662957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d0060088d6'
down_revision: Union[str, Sequence[str], None] = '1b9203eb9391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_userName_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_userName_key'), 'users', ['userName'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
