"""added foreign key in dealers table

Revision ID: 423f79af14fc
Revises: 132dd92701d6
Create Date: 2026-08-21 17:09:59.331338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423f79af14fc'
down_revision: Union[str, Sequence[str], None] = '132dd92701d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealers', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'dealers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dealers', type_='foreignkey')
    op.drop_column('dealers', 'user_id')
    # ### end Alembic commands ###
