"""add dealer user name unique constraint

Revision ID: cdac86ce54c2
Revises: 423f79af14fc
Create Date: 2026-08-21 18:58:03.584737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdac86ce54c2'
down_revision: Union[str, Sequence[str], None] = '423f79af14fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_dealers_user_id_name', 'dealers', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_dealers_user_id_name', 'dealers', type_='unique')
    # ### end Alembic commands ###
