ACCESS_TOKEN_EXPIRES_MINUTES: int = 15
ACCESS_TOKEN_EXPIRES_SECONDS: int = ACCESS_TOKEN_EXPIRES_MINUTES * 60
REFRESH_TOKEN_EXPIRES_DAYS: int = 30
REFRESH_COOKIE_MAX_AGE: int = REFRESH_TOKEN_EXPIRES_DAYS * 24 * 60 * 60